/**
 * 🎫 Centralized Error Codes
 * Standardized codes for backend & frontend consistency.
 */
const ErrorCodes = {
    // Auth & Identity
    AUTH_INVALID: 'AUTH_INVALID',
    AUTH_MISSING: 'AUTH_MISSING',
    AUTH_EXPIRED: 'AUTH_EXPIRED',
    AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
    SESSION_COMPROMISED: 'SESSION_COMPROMISED',
    
    // Billing & Trial
    TRIAL_EXPIRED: 'TRIAL_EXPIRED',
    BILLING_REQUIRED: 'BILLING_REQUIRED',
    PAYMENT_FAILED: 'PAYMENT_FAILED',
    LIMIT_REACHED: 'LIMIT_REACHED',
    
    // Tenant & Admin
    TENANT_SUSPENDED: 'TENANT_SUSPENDED',
    INSTITUTION_INACTIVE: 'INSTITUTION_INACTIVE',
    
    // Security & Logic
    WEBHOOK_SIGNATURE_INVALID: 'WEBHOOK_SIGNATURE_INVALID',
    SECURITY_VIOLATION: 'SECURITY_VIOLATION',
    RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    
    // System
    SYSTEM_ERROR: 'SYSTEM_ERROR',
    MAINTENANCE_MODE: 'MAINTENANCE_MODE',
    SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE',
    RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED'
};

module.exports = ErrorCodes;
